# Generated by Django 6.0 on 2026-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide', models.CharField(max_length=70)),
                ('microorganism_name', models.CharField(max_length=100)),
                ('protein', models.CharField(blank=True, max_length=70, null=True)),
                ('gene', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.TextField(max_length=500)),
                ('doi', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoEvidencePesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide', models.CharField(max_length=200)),
                ('evidence_of_biodegradation', models.CharField(default='No evidence', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide', models.CharField(max_length=200)),
                ('microorganism', models.CharField(blank=True, max_length=200, null=True)),
                ('phylum', models.CharField(blank=True, max_length=200, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('strain', models.CharField(blank=True, max_length=200, null=True)),
                ('rrna_16s', models.CharField(blank=True, max_length=200, null=True, verbose_name='16s rRNA')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('substrate', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('evidence_by_microbe', models.TextField(blank=True, null=True)),
                ('microbe_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('isolation_environment', models.CharField(blank=True, max_length=255, null=True)),
                ('degradation_time_days', models.CharField(blank=True, max_length=100, null=True)),
                ('isolation_location', models.CharField(blank=True, max_length=200, null=True)),
                ('enzyme', models.CharField(blank=True, max_length=200, null=True)),
                ('evidence_of_enzyme', models.TextField(blank=True, null=True)),
                ('enzyme_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('genbank_id', models.CharField(blank=True, max_length=200, null=True)),
                ('enzyme_sequence', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
