# Generated by Django 4.2.27 on 2026-01-21 05:33

from django.db import migrations, models
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='noevidencepesticide',
            options={'ordering': ['pesticide']},
        ),
        migrations.AlterModelOptions(
            name='pesticide',
            options={'ordering': ['pesticide']},
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='enzyme_equipment',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='enzyme_sequence',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='family',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='genbank_id',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='microbe_equipment',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='rrna_16s',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='strain',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='substrate',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='noevidencepesticide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noevidencepesticide',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='doi',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='evidence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='gene',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='microorganism_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='pesticide',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='protein',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noevidencepesticide',
            name='evidence_of_biodegradation',
            field=models.CharField(default='No experimental biodegradation evidence found', max_length=255),
        ),
        migrations.AlterField(
            model_name='noevidencepesticide',
            name='pesticide',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='pesticide',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='noevidencepesticide',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pesticide'), name='uq_noevidence_pesticide_lower'),
        ),
        migrations.AddConstraint(
            model_name='pesticide',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pesticide'), name='uq_pesticide_lower'),
        ),
    ]
