# Generated by Django 4.2.27 on 2026-01-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_datasubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pesticide',
            name='uq_pesticide_lower',
        ),
    ]
