# Generated by Django 4.2.27 on 2026-01-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_pesticide_uq_pesticide_lower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='noevidencepesticide',
            name='uq_noevidence_pesticide_lower',
        ),
    ]
