# Generated by Django 4.2.27 on 2026-01-21 11:37

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_noevidencepesticide_uq_noevidence_pesticide_lower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticide',
            options={'ordering': ['pesticide', 'microorganism']},
        ),
        migrations.AddField(
            model_name='pesticide',
            name='enzyme_name_reported',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='noevidencepesticide',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pesticide'), name='uq_noevidence_pesticide_lower'),
        ),
    ]
