# Generated by Django 4.2.27 on 2026-01-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_pesticide_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='noevidencepesticide',
            name='uq_noevidence_pesticide_lower',
        ),
    ]
