# Generated by Django 4.2.27 on 2026-01-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_noevidencepesticide_uq_noevidence_pesticide_lower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide', models.CharField(blank=True, max_length=255, null=True)),
                ('microorganism', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_type', models.CharField(blank=True, max_length=255, null=True)),
                ('enzyme_class', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_protein_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pbdb_protein_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('ncbi_protein_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('uniprot_accession', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence_available', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
