# Generated by Django 4.2.27 on 2026-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_proteinrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinrecord',
            name='fasta_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteinrecord',
            name='pesticidedb_protein_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
