# Generated by Django 4.2.27 on 2026-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_proteinrecord_fasta_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('ncbi_protein_accession', models.CharField(max_length=50)),
                ('pesticidedb_protein_id', models.CharField(max_length=50)),
                ('pesticide', models.CharField(blank=True, max_length=255, null=True)),
                ('microorganism', models.CharField(blank=True, max_length=255, null=True)),
                ('enzyme_class', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_protein_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family_size', models.IntegerField(blank=True, null=True)),
                ('family_confidence', models.CharField(blank=True, max_length=20, null=True)),
                ('hmmer_family', models.CharField(blank=True, max_length=100, null=True)),
                ('identity', models.FloatField(blank=True, null=True)),
                ('evalue', models.FloatField(blank=True, null=True)),
                ('bitscore', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='proteinrecord',
            name='pesticidedb_protein_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
