# Generated by Django 4.2.27 on 2026-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_annotationresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('result_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
