# Generated by Django 4.2.27 on 2026-06-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_proteinrecord_collection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegradationPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('microorganism', models.CharField(blank=True, max_length=255)),
                ('completeness', models.CharField(choices=[('COMPLETE', 'Complete mineralization reported'), ('PARTIAL', 'Partial degradation reported'), ('PROPOSED', 'Proposed pathway')], default='PARTIAL', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('reference', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['pesticide', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DegradationPathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('substrate', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('gene', models.CharField(blank=True, max_length=255)),
                ('enzyme', models.CharField(blank=True, max_length=255)),
                ('microorganism', models.CharField(blank=True, max_length=255)),
                ('evidence_type', models.CharField(choices=[('PURIFIED_ENZYME', 'Purified/recombinant enzyme'), ('GENETIC', 'Gene knockout/expression evidence'), ('METABOLITE', 'Metabolite experimentally detected'), ('WHOLE_CELL', 'Whole-cell or crude extract'), ('PROPOSED', 'Proposed/inferred step')], default='PROPOSED', max_length=30)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='base.degradationpathway')),
                ('protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_steps', to='base.proteinrecord')),
            ],
            options={
                'ordering': ['pathway', 'step_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='degradationpathwaystep',
            constraint=models.UniqueConstraint(fields=('pathway', 'step_order'), name='unique_pathway_step_order'),
        ),
    ]
