# Generated by Django 4.2.27 on 2026-07-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_degradationpathway_degradationpathwaystep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('PESTICIDE', 'Parent pesticide'), ('METABOLITE', 'Metabolite/intermediate'), ('END_PRODUCT', 'End product'), ('UNKNOWN', 'Unknown/unresolved compound')], default='METABOLITE', max_length=30)),
                ('cas_number', models.CharField(blank=True, max_length=100)),
                ('pubchem_cid', models.CharField(blank=True, max_length=100)),
                ('smiles', models.TextField(blank=True)),
                ('inchikey', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiteratureReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pmid', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PathwayEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(blank=True, max_length=255)),
                ('directness', models.CharField(choices=[('DIRECT', 'Direct evidence'), ('INDIRECT', 'Indirect evidence'), ('PROPOSED', 'Proposed/inferred')], default='DIRECT', max_length=20)),
                ('confidence', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='base.degradationpathway')),
                ('pesticide_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_evidence', to='base.pesticide')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_evidence', to='base.literaturereference')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='base.degradationpathwaystep')),
            ],
            options={
                'ordering': ['pathway', 'step__step_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='degradationpathway',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='pathways', to='base.literaturereference'),
        ),
        migrations.AddField(
            model_name='degradationpathwaystep',
            name='product_compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_steps_as_product', to='base.compound'),
        ),
        migrations.AddField(
            model_name='degradationpathwaystep',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='pathway_steps', to='base.literaturereference'),
        ),
        migrations.AddField(
            model_name='degradationpathwaystep',
            name='substrate_compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_steps_as_substrate', to='base.compound'),
        ),
    ]
