# Generated by Django 4.2.27 on 2026-07-12 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_compound_literaturereference_pathwayevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='approve_biodegradation_record',
            field=models.BooleanField(default=False, help_text='If checked, admin approval can create a curated microorganism/pesticide evidence record.'),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='approve_protein_record',
            field=models.BooleanField(default=False, help_text='If checked, admin approval can create a protein record when protein/gene evidence is supplied.'),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='detected_sections',
            field=models.CharField(blank=True, help_text='Automatically suggested database sections related to this submission.', max_length=255),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='flag_for_pathway_curation',
            field=models.BooleanField(default=False, help_text='Use when the paper appears to contain metabolite, product, pathway, or transformation information.'),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='imported_biodegradation_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='base.pesticide'),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='imported_protein_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='base.proteinrecord'),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('NEEDS_REVISION', 'Needs revision'), ('APPROVED', 'Approved and imported'), ('PARTIALLY_IMPORTED', 'Partially imported'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
