# Generated by Django on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_datasubmission_approve_biodegradation_record_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisitCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="site", max_length=50, unique=True)),
                ("total_visits", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site visit counter",
                "verbose_name_plural": "site visit counters",
            },
        ),
    ]
