# Generated by Django on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_sitevisitcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticide",
            name="culture_type",
            field=models.CharField(
                blank=True,
                help_text="Examples: Individual strain, Consortium member, Microbial community, Enrichment culture, Isolate group.",
                max_length=80,
                null=True,
            ),
        ),
    ]
