# Generated by Django on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_pesticide_culture_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticide",
            name="culture_group",
            field=models.CharField(
                blank=True,
                help_text="Shared source culture, consortium, enrichment, or community name for grouped records.",
                max_length=255,
                null=True,
            ),
        ),
    ]
