# Generated by Django on 2026-07-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_pesticide_culture_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pesticide",
            name="culture_group",
        ),
    ]
