# Generated by Django 4.2.27 on 2026-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_pesticide_culture_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='metabolite_or_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
